version: '3.7'

services:
  yolo:
    image: bertytech/yolo:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 80:8000
    environment:
      - BUILDKITE_TOKEN=${YOLO_BUILDKITE_TOKEN}
      - CIRCLE_TOKEN=${YOLO_CIRCLE_TOKEN}
      - GITHUB_TOKEN=${YOLO_GITHUB_TOKEN}
      - BINTRAY_TOKEN=${YOLO_BINTRAY_TOKEN}
      - BINTRAY_USERNAME=${YOLO_BINTRAY_USERNAME}
      - BEARER_SECRETKEY=${YOLO_BEARER_SECRETKEY}
    command: -v server --cors-allowed-origins="*" --max-builds=30 --db-path=/data/yolo.sqlite --basic-auth-password="${YOLO_BASIC_AUTH_PASSWORD}" --request-timeout=10s --shutdown-timeout=11s --http-cache-path=/data/httpcache --artifacts-cache-path=/data/artifacts-cache
    labels:
      com.centurylinklabs.watchtower.enable: "true"
