version: '3.7'

services:
  yolo:
    image: bertytech/yolo:latest
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./data:/data
    expose:
      - 8000
    environment:
      - BUILDKITE_TOKEN=${YOLO_BUILDKITE_TOKEN}
      - CIRCLE_TOKEN=${YOLO_CIRCLE_TOKEN}
      - GITHUB_TOKEN=${YOLO_GITHUB_TOKEN}
      - BINTRAY_TOKEN=${YOLO_BINTRAY_TOKEN}
      - BINTRAY_USERNAME=${YOLO_BINTRAY_USERNAME}
      - BEARER_SECRETKEY=${YOLO_BEARER_SECRETKEY}
    command: -v server --cors-allowed-origins="*" --max-builds=30 --db-path=/data/yolo.sqlite --basic-auth-password="${YOLO_BASIC_AUTH_PASSWORD}" --request-timeout=10s --shutdown-timeout=11s --http-cache-path=/data/httpcache --artifacts-cache-path=/data/artifacts-cache
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
      # traefik specific labels
      - 'traefik.enable=true'
      - 'traefik.http.routers.yolo.rule=Host(`yolo.berty.io`)'
      - 'traefik.http.routers.yolo.service=yolo'
      - 'traefik.http.routers.yolo.entryPoints=https'
      - 'traefik.http.routers.yolo.tls=true'
      - 'traefik.http.routers.yolo.tls.certresolver=cf'
      - 'traefik.http.routers.yolo.tls.domains[0].main=berty.io'
      - 'traefik.http.routers.yolo.tls.domains[0].sans=yolo.berty.io'

      - 'traefik.http.services.yolo.loadbalancer.server.port=8000'
